"""
Pre-build step: compress the settings web page and embed it in the firmware.

  web/index.html   (edit THIS - a normal, syntax-highlightable HTML file)
        |
        |  gzip -9, deterministic (mtime=0)
        v
  src/WebPage_gz.h  (AUTO-GENERATED byte array - never edit, never commit)

Why minify + gzip: the readable source is roughly 119 KB. Sent raw over a
marginal WiFi link it routinely stalled or arrived half-rendered. Conservative
build-time minification followed by gzip reduces it to roughly 22 KB. Every
browser sends `Accept-Encoding: gzip`, and `handleRoot()` serves the compressed
bytes verbatim; there is no runtime compression cost on the ESP32.

Why embedded in flash rather than SPIFFS: the page then always ships with the
firmware (no `pio run -t uploadfs` step to forget) and it survives a SPIFFS
reformat - which is exactly the situation where you most need the web UI to
reconfigure the clock. See HANDOFF.md.

The output is byte-for-byte deterministic, and is only rewritten when it
actually changes, so an unchanged page does not force main.cpp to recompile.
"""

import gzip
import os
import re

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
SRC_HTML = os.path.join(PROJECT_DIR, "web", "index.html")
OUT_HEADER = os.path.join(PROJECT_DIR, "src", "WebPage_gz.h")

BYTES_PER_LINE = 16


def minify_for_delivery(raw):
    """Conservatively remove delivery-only HTML/CSS whitespace.

    The editable source stays readable. JavaScript contents and text nodes are
    deliberately left alone; only comments, CSS formatting, and whitespace
    between HTML tags are removed.
    """
    html = raw.decode("utf-8")
    html = re.sub(r"<!--(?!\[if\b).*?-->", "", html, flags=re.DOTALL)

    def minify_style(match):
        css = re.sub(r"/\*.*?\*/", "", match.group(1), flags=re.DOTALL)
        css = re.sub(r"\s+", " ", css)
        css = re.sub(r"\s*([{}:;,>])\s*", r"\1", css)
        return "<style>" + css.strip() + "</style>"

    html = re.sub(r"<style>(.*?)</style>", minify_style, html,
                  flags=re.DOTALL | re.IGNORECASE)
    html = re.sub(r">\s+<", "><", html)
    return html.encode("utf-8")


def render_header(gz_bytes):
    lines = []
    for i in range(0, len(gz_bytes), BYTES_PER_LINE):
        chunk = gz_bytes[i:i + BYTES_PER_LINE]
        lines.append("  " + " ".join("0x%02x," % b for b in chunk))
    body = "\n".join(lines)

    return (
        "// AUTO-GENERATED by scripts/build_web.py - DO NOT EDIT, DO NOT COMMIT.\n"
        "// Source: web/index.html (edit that file instead; this is regenerated\n"
        "// on every build and is listed in .gitignore).\n"
        "#ifndef WEBPAGE_GZ_H\n"
        "#define WEBPAGE_GZ_H\n"
        "\n"
        "#include <pgmspace.h>\n"
        "#include <stdint.h>\n"
        "\n"
        "// gzip-compressed settings page. Served as-is with the\n"
        "// `Content-Encoding: gzip` header; the browser decompresses it.\n"
        "const unsigned int WEBPAGE_GZ_LEN = %d;\n"
        "const uint8_t WEBPAGE_GZ[] PROGMEM = {\n"
        "%s\n"
        "};\n"
        "\n"
        "#endif // WEBPAGE_GZ_H\n"
    ) % (len(gz_bytes), body)


def build_web_page(*args, **kwargs):
    if not os.path.isfile(SRC_HTML):
        raise RuntimeError(
            "web/index.html not found - the settings page source is missing. "
            "Expected at: %s" % SRC_HTML
        )

    with open(SRC_HTML, "rb") as f:
        raw = f.read()

    # mtime=0 keeps the output byte-for-byte stable across runs, so an
    # unchanged page does not look "modified" and trigger a pointless rebuild.
    delivered = minify_for_delivery(raw)
    gz = gzip.compress(delivered, compresslevel=9, mtime=0)
    header = render_header(gz)

    existing = None
    if os.path.isfile(OUT_HEADER):
        with open(OUT_HEADER, "r") as f:
            existing = f.read()

    if existing == header:
        print("Web page unchanged (%d B source -> %d B minified -> %d B gzip), reusing WebPage_gz.h"
              % (len(raw), len(delivered), len(gz)))
        return

    with open(OUT_HEADER, "w") as f:
        f.write(header)

    print("Web page embedded: %d B source -> %d B minified -> %d B gzip (%.1fx smaller) -> src/WebPage_gz.h"
          % (len(raw), len(delivered), len(gz), len(raw) / float(len(gz))))


build_web_page()
